create table bar_info;


INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Linger', 39.759526, -105.0136293, 'LoHi', 'http://lingerdenver.com/', 'http://lingerdenver.com/pdf/Linger_HappyHour_October_2016.pdf', 'http://cdn.justluxe.com/articles/images/news/lingerrestaurant.jpg', false, NULL, true, '4:00pm - 6:30pm', true, '4:00pm - 6:30pm', true, '4:00pm - 6:30pm', true, '4:00pm - 6:30pm', false, null, false, null);

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Lola', 39.7592294, -105.0107865, 'LoHi', 'http://www.loladenver.com/', 'http://www.loladenver.com/menus/happy-hour/', 'http://guide.denverpost.com/media/photos/full/lola_600x600.JPG', true, '4:00pm - Close', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '2:30pm - 5:00pm', true, '2:30pm - 5:00pm');

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Dunbar Kitchen & Tap House', 39.756242, -104.975893, 'Rino/Five Points', 'http://www.dunbarkitchenandtaphouse.com/', 'http://www.dunbarkitchenandtaphouse.com/new-menu/', 'https://s3-media1.fl.yelpcdn.com/bphoto/7kKaMWhDPu8Qq0RSgCz5IQ/o.jpg', true, '2:30pm - 6:30pm', true, '2:30pm - 6:30pm', true, '2:30pm - 6:30pm', true, '2:30pm - 6:30pm', true, '2:30pm - 6:30pm', true, '2:30pm - 6:30pm', true, '2:30pm - 6:30pm');

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Central Bistro and Bar', 39.759193, -105.0084136, 'LoHi', 'http://www.centralbistrobar.com/', 'http://www.centralbistrobar.com/menu-1/', 'https://media-cdn.tripadvisor.com/media/photo-s/03/07/ce/f5/central-bistro-and-bar.jpg', false, null, true, '2:00pm - Close', true, '2:00pm - 6:00pm', true, '2:00pm - 6:00pm', true, '2:00pm - 6:00pm', true, '2:00pm - 6:00pm', false, null);

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Old Major', 39.763547, -105.010789, 'LoHi', 'http://oldmajordenver.com/', 'http://oldmajordenver.com/menu/', 'http://images1.westword.com/imager/old-major/u/original/5180598/8617647.0.jpg', false, null, false, null, true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm');

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Humbolt Farm-Fish-Wine', 39.743485, -104.969341, 'Uptown', 'http://humboldtrestaurant.com/', 'http://humboldtrestaurant.com/', 'http://humboldtrestaurant.com/wp-content/uploads/2015/04/tmg-slideshow_xxl-2.jpeg', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm');

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('The Way Back', 39.769235, -105.041319, 'Highlands', 'http://thewaybackdenver.com/#local-seasonal', 'http://thewaybackdenver.com/menus-1/', 'http://images1.westword.com/imager/u/original/7859583/way-back-ext2.jpg', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', false, null, false, null);

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Larimer Lounge', 39.7599262, -104.9838041, 'Curtis Park', 'http://www.larimerlounge.com/', 'http://www.larimerlounge.com/happy_hour.cfm', 'http://www.milehighhappyhour.com/wp-content/uploads/2014/04/Larimer-Lounge3-1000x500.jpg', true, '4:00pm - 8:00pm', true, '4:00pm - 8:00pm', true, '4:00pm - 8:00pm', true, '4:00pm - 8:00pm', true, '4:00pm - 8:00pm', false, null, false, null);

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Ace', 39.743502, -104.980749, 'Uptown', 'http://www.aceeatserve.com/menus/main', 'http://www.aceeatserve.com/menus/happyhour', 'https://cdn1.vox-cdn.com/uploads/chorus_image/image/46326706/upload.0.0.0.jpg', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm',  true, '3:00pm - 6:00pm',  true, '3:00pm - 6:00pm',  true, '3:00pm - 6:00pm', false, null, false, null);

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Gozo', 39.715948, -104.9871319, 'South Broadway', 'http://gozodenver.com/', 'http://gozodenver.com/happy-hour/', 'http://images2.westword.com/imager/gozo/u/original/6030730/9860624.0.jpg', true, '3:00pm - 6:00pm', true, '3:00pm - 6:00pm',  true, '3:00pm - 6:00pm',  true, '3:00pm - 6:00pm',  true, '3:00pm - 6:00pm', false, null, false, null);

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Vesper Lounge', 39.727443, -104.983996, 'Central Denver', 'http://www.vesperdenver.com/', 'http://vesperdenver.com/menus/VesperHappyHour.pdf', 'http://denver.thedrinknation.com/images/bars/VesperLoungeDENV.jpg', true, '4:00pm - 2:00am', true, '4:00pm - 2:00am',  true, '4:00pm - 2:00am',  true, '4:00pm - 2:00am',  true, '4:00pm - 2:00am', true, '2:00pm - 2:00am', true, '2:00pm - 2:00am');

INSERT INTO bar_info(restaurant_name, latitude, longitude, neighborhood, website_url, menu_url, image_url, monday, monday_time, tuesday, tuesday_time, wednesday, wednesday_time, thursday, thursday_time, friday, friday_time, saturday, saturday_time, sunday, sunday_time)
VALUES ('Leña', 39.7171992, -104.9873205, 'South Broadway', 'http://www.lenadenver.com/', 'http://www.lenadenver.com/happy-hour', 'http://wandermelon.com/wordpress/wp-content/uploads/2014/12/004_Lena_570.jpg', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm', true, '4:00pm - 6:00pm',  true, '4:00pm - 6:00pm',  true, '4:00pm - 6:00pm', false, null, false, null);